[functions]
[functions.doc-parser]
verify_jwt = true

[functions.vector-processor]
verify_jwt = true

[functions.job-processor]
verify_jwt = true

[realtime]
enabled = true

[realtime.tables]
[realtime.tables.realtime_progress_updates]
enabled = true
