#!/bin/bash

# Test script to demonstrate fail-fast behavior of configuration loading

echo "🧪 Testing Supabase Production Configuration Loading"
echo "=================================================="
echo ""

echo "1️⃣ Testing with no environment variables (should fail):"
echo "--------------------------------------------------------"
./load_production_config.sh
echo ""

echo "2️⃣ Testing with partial environment variables (should fail):"
echo "------------------------------------------------------------"
export SUPABASE_PROJECT_ID="mrbigmtnadjtyepxqefa"
export SUPABASE_ORG_ID="olcuvzctdaqfqgwidwrp"
export DATABASE_HOST="db.mrbigmtnadjtyepxqefa.supabase.co"
export DATABASE_PORT="5432"
export DATABASE_NAME="postgres"
export DATABASE_USER="postgres"
export DATABASE_PASSWORD="test-password"
export DATABASE_MAX_CONNECTIONS="100"
export DATABASE_POOL_SIZE="20"
export SITE_URL="https://insurance-navigator.vercel.app"
export ADDITIONAL_REDIRECT_URLS="https://insurance-navigator.vercel.app/auth/callback,https://insurance-navigator.vercel.app/dashboard"
export JWT_EXPIRY="3600"
export STORAGE_BUCKET_NAME="insurance_documents_prod"
export STORAGE_FILE_SIZE_LIMIT="104857600"
export STORAGE_ALLOWED_MIME_TYPES="application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,application/rtf"
export REALTIME_MAX_CONNECTIONS="1000"
export EDGE_FUNCTIONS_MAX_EXECUTION_TIME="30"
export MONITORING_METRICS_RETENTION_DAYS="30"
export MONITORING_LOG_RETENTION_DAYS="7"
export BACKUP_SCHEDULE="0 2 * * *"
export BACKUP_RETENTION_DAYS="30"
export SUPABASE_URL="https://mrbigmtnadjtyepxqefa.supabase.co"
export SUPABASE_ANON_KEY="test-anon-key"
export SUPABASE_SERVICE_ROLE_KEY="test-service-role-key"

./load_production_config.sh
echo ""

echo "3️⃣ Testing with all environment variables (should succeed):"
echo "------------------------------------------------------------"
export SUPABASE_PROJECT_ID="mrbigmtnadjtyepxqefa"
export SUPABASE_ORG_ID="olcuvzctdaqfqgwidwrp"
export DATABASE_HOST="db.mrbigmtnadjtyepxqefa.supabase.co"
export DATABASE_PORT="5432"
export DATABASE_NAME="postgres"
export DATABASE_USER="postgres"
export DATABASE_PASSWORD="test-password"
export DATABASE_MAX_CONNECTIONS="100"
export DATABASE_POOL_SIZE="20"
export SITE_URL="https://insurance-navigator.vercel.app"
export ADDITIONAL_REDIRECT_URLS="https://insurance-navigator.vercel.app/auth/callback,https://insurance-navigator.vercel.app/dashboard"
export JWT_EXPIRY="3600"
export STORAGE_BUCKET_NAME="insurance_documents_prod"
export STORAGE_FILE_SIZE_LIMIT="104857600"
export STORAGE_ALLOWED_MIME_TYPES="application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain,application/rtf"
export REALTIME_MAX_CONNECTIONS="1000"
export EDGE_FUNCTIONS_MAX_EXECUTION_TIME="30"
export MONITORING_METRICS_RETENTION_DAYS="30"
export MONITORING_LOG_RETENTION_DAYS="7"
export BACKUP_SCHEDULE="0 2 * * *"
export BACKUP_RETENTION_DAYS="30"
export SUPABASE_URL="https://mrbigmtnadjtyepxqefa.supabase.co"
export SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYmlnbXRuYWRqdHllcHhxZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5NTA1NTIsImV4cCI6MjA3NTUyNjU1Mn0.PTDSvO868CTav2ArHMIfwqXw0RJDzS7-LuUuP1nKNxI"
export SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYmlnbXRuYWRqdHllcHhxZWZhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTk1MDU1MiwiZXhwIjoyMDc1NTI2NTUyfQ.QVhRPZmpdaeL13qnqifig64I-1izTaPMqovni_2hcgY"

./load_production_config.sh
echo ""

echo "✅ Test completed!"
echo ""
echo "📋 Summary:"
echo "   - Configuration loading fails fast when variables are missing"
echo "   - Clear error messages are provided"
echo "   - All required variables must be set for success"
echo "   - No default values are used - explicit configuration is required"
