# Development Environment Configuration
# 003 Worker Refactor - Local Development Environment with Supabase

environment: development
debug: true
testing: true

# Database Configuration
database:
  url: postgresql://postgres:postgres@supabase_db_insurance_navigator:5432/postgres?sslmode=disable
  schema: upload_pipeline
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600

# API Server Configuration
api:
  host: 0.0.0.0
  port: 8000
  workers: 2
  reload: true
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  trusted_hosts:
    - "localhost"
    - "127.0.0.1"
    - "*.render.com"

# Worker Configuration
worker:
  max_jobs: 10
  poll_interval: 5
  max_retries: 3
  retry_delay: 10
  health_check_interval: 30
  graceful_shutdown_timeout: 60

# External Services Configuration
external_services:
  llamaparse:
    api_url: ${LLAMAPARSE_API_URL}
    api_key: ${LLAMAPARSE_API_KEY}
    timeout: 120
    max_retries: 3
    retry_delay: 5
  
  openai:
    api_url: ${OPENAI_API_URL}
    api_key: ${OPENAI_API_KEY}
    timeout: 60
    max_retries: 3
    retry_delay: 5
    batch_size: 256
    rate_limit_delay: 1

# Storage Configuration
storage:
  environment: development
  url: http://supabase_kong_insurance_navigator:8000
  supabase:
    url: http://supabase_kong_insurance_navigator:8000
    anon_key: ${SUPABASE_ANON_KEY}
    service_role_key: ${SUPABASE_SERVICE_ROLE_KEY}
    storage_url: http://supabase_kong_insurance_navigator:8000
  
  buckets:
    raw:
      name: raw
      public: false
      max_file_size: 268435456  # 256MB
      allowed_mime_types:
        - application/pdf
    
    parsed:
      name: parsed
      public: false
      max_file_size: 10485760   # 10MB
      allowed_mime_types:
        - text/markdown
        - text/plain

# Monitoring Configuration
monitoring:
  enabled: true
  log_level: DEBUG
  log_format: json
  metrics_collection: true
  alerting: false