# Render.com Workflow Testing Deployment Configuration
# Phase 2: Cloud Deployment Testing
# Deploys API and Worker services to Render.com with production Supabase integration

services:
  # API Service - Document upload and processing pipeline
  - type: web
    name: insurance-navigator-api-workflow-testing
    env: docker
    plan: starter
    dockerfilePath: ./api/upload_pipeline/Dockerfile
    region: oregon
    branch: main
    port: 8000
    healthCheckPath: /health
    # Render optimizations for faster startup
    buildCommand: "echo 'Using Docker build - no additional build command needed'"
    preDeployCommand: "echo 'Pre-deploy optimization complete'"
    # Optimized startup command for workflow testing
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --timeout-keep-alive 75"
    healthCheckTimeout: 180
    numReplicas: 1
    autoscaling:
      enabled: true
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
    envVars:
      # Production Supabase Configuration (from Phase 1)
      - key: SUPABASE_URL
        value: ***REMOVED***
      - key: SUPABASE_ANON_KEY
        value: ***REMOVED***.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudnd6a2RibGtua2t6dHF5Zm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODA0NTYsImV4cCI6MjA2NzI1NjQ1Nn0.k0QHYOgm4EilyyTml57kCGDpbikpEtJCzq-qzGYQZqY
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ***REMOVED***.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudnd6a2RibGtua2t6dHF5Zm51Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTY4MDQ1NiwiZXhwIjoyMDY3MjU2NDU2fQ.9Urox9-xr5TJz8a9LbSZsGUMcSTThc3QM6XDMJD-j-o
      
      # Database Configuration
      - key: DATABASE_URL
        value: postgresql://postgres:beqhar-qincyg-Syxxi8@db.znvwzkdblknkkztqyfnu.supabase.co:5432/postgres
      - key: POOLER_URL
        value: postgresql://postgres.znvwzkdblknkkztqyfnu:beqhar-qincyg-Syxxi8@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      
      # Upload Pipeline Configuration
      - key: UPLOAD_PIPELINE_SUPABASE_URL
        value: ***REMOVED***
      - key: UPLOAD_PIPELINE_SUPABASE_ANON_KEY
        value: ***REMOVED***.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudnd6a2RibGtua2t6dHF5Zm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODA0NTYsImV4cCI6MjA2NzI1NjQ1Nn0.k0QHYOgm4EilyyTml57kCGDpbikpEtJCzq-qzGYQZqY
      - key: UPLOAD_PIPELINE_SUPABASE_SERVICE_ROLE_KEY
        value: ***REMOVED***.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudnd6a2RibGtua2t6dHF5Zm51Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTY4MDQ1NiwiZXhwIjoyMDY3MjU2NDU2fQ.9Urox9-xr5TJz8a9LbSZsGUMcSTThc3QM6XDMJD-j-o
      
      # External API Configuration
      - key: OPENAI_API_KEY
        value: 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
      - key: LLAMAPARSE_API_KEY
        value: llx-X9bRG4r7mq5Basype0fCvfvlj1372pDdQXi7KaxVqkRlkoSb
      - key: LLAMAPARSE_BASE_URL
        value: https://api.cloud.llamaindex.ai
      
      # Workflow Testing Environment Overrides
      - key: UPLOAD_PIPELINE_ENVIRONMENT
        value: workflow_testing
      - key: UPLOAD_PIPELINE_STORAGE_ENVIRONMENT
        value: workflow_testing
      - key: UPLOAD_PIPELINE_STORAGE_URL
        value: ***REMOVED***
      - key: SERVICE_MODE
        value: HYBRID
      - key: SECURITY_BYPASS_ENABLED
        value: false
      
      # Cross-Platform Configuration
      - key: API_BASE_URL
        value: https://insurance-navigator-api-workflow-testing.onrender.com
      - key: CORS_ORIGINS
        value: https://insurance-navigator-frontend-workflow-testing.vercel.app
      
      # Health Check Configuration
      - key: HEALTH_CHECK_ENABLED
        value: true
      - key: HEALTH_CHECK_INTERVAL
        value: 30
      
      # Render startup optimizations
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: UVICORN_WORKERS
        value: "1"
      - key: STARTUP_TIMEOUT
        value: "180"
      - key: KEEP_ALIVE
        value: "75"
      - key: MAX_REQUESTS
        value: "1000"
      - key: MAX_REQUESTS_JITTER
        value: "100"
      
      # Testing Isolation Configuration
      - key: TEST_SCHEMA_PREFIX
        value: workflow_testing_
      - key: TEST_TABLE_PREFIX
        value: wt_
      - key: TEST_STORAGE_BUCKET
        value: workflow-testing-documents
      - key: TEST_STORAGE_PREFIX
        value: workflow_testing/
      - key: TEST_USER_PREFIX
        value: test_user_
      - key: TEST_USER_DOMAIN
        value: workflow-testing.local
      
      # Cost Control and Safety
      - key: ENABLE_COST_MONITORING
        value: true
      - key: DAILY_COST_LIMIT
        value: 50.00
      - key: ALERT_ON_COST_THRESHOLD
        value: true
      - key: ENABLE_AUTO_CLEANUP
        value: true
      - key: CLEANUP_INTERVAL
        value: 3600
      - key: MAX_TEST_DATA_AGE
        value: 86400
      
      # Monitoring and Logging
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: ENABLE_DEBUG_LOGGING
        value: true
      - key: ENABLE_METRICS_COLLECTION
        value: true
      - key: METRICS_INTERVAL
        value: 60
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
      - key: ENABLE_ERROR_TRACKING
        value: true
      - key: ERROR_SAMPLE_RATE
        value: 1.0

  # Worker Service - Background job processing
  - type: worker
    name: insurance-navigator-worker-workflow-testing
    env: docker
    plan: starter
    dockerfilePath: ./backend/workers/Dockerfile
    region: oregon
    branch: main
    # Worker-specific settings
    numReplicas: 1
    autoscaling:
      enabled: true
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 80
    envVars:
      # Production Supabase Configuration (from Phase 1)
      - key: SUPABASE_URL
        value: ***REMOVED***
      - key: SUPABASE_ANON_KEY
        value: ***REMOVED***.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudnd6a2RibGtua2t6dHF5Zm51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODA0NTYsImV4cCI6MjA2NzI1NjQ1Nn0.k0QHYOgm4EilyyTml57kCGDpbikpEtJCzq-qzGYQZqY
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ***REMOVED***.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpudnd6a2RibGtua2t6dHF5Zm51Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MTY4MDQ1NiwiZXhwIjoyMDY3MjU2NDU2fQ.9Urox9-xr5TJz8a9LbSZsGUMcSTThc3QM6XDMJD-j-o
      
      # Database Configuration
      - key: DATABASE_URL
        value: postgresql://postgres:beqhar-qincyg-Syxxi8@db.znvwzkdblknkkztqyfnu.supabase.co:5432/postgres
      - key: POOLER_URL
        value: postgresql://postgres.znvwzkdblknkkztqyfnu:beqhar-qincyg-Syxxi8@aws-0-us-west-1.pooler.supabase.com:6543/postgres
      
      # External API Configuration
      - key: OPENAI_API_KEY
        value: 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
      - key: LLAMAPARSE_API_KEY
        value: llx-X9bRG4r7mq5Basype0fCvfvlj1372pDdQXi7KaxVqkRlkoSb
      - key: LLAMAPARSE_BASE_URL
        value: https://api.cloud.llamaindex.ai
      
      # Workflow Testing Environment Overrides
      - key: UPLOAD_PIPELINE_ENVIRONMENT
        value: workflow_testing
      - key: UPLOAD_PIPELINE_STORAGE_ENVIRONMENT
        value: workflow_testing
      - key: UPLOAD_PIPELINE_STORAGE_URL
        value: ***REMOVED***
      - key: SERVICE_MODE
        value: HYBRID
      - key: SECURITY_BYPASS_ENABLED
        value: false
      
      # Cross-Platform Configuration
      - key: API_BASE_URL
        value: https://insurance-navigator-api-workflow-testing.onrender.com
      
      # Worker Configuration
      - key: WORKER_HEALTH_CHECK_ENABLED
        value: true
      - key: WORKER_HEALTH_CHECK_INTERVAL
        value: 30
      - key: WORKER_POLL_INTERVAL
        value: 5
      - key: WORKER_MAX_JOBS
        value: 10
      - key: WORKER_MAX_RETRIES
        value: 3
      
      # Testing Isolation Configuration
      - key: TEST_SCHEMA_PREFIX
        value: workflow_testing_
      - key: TEST_TABLE_PREFIX
        value: wt_
      - key: TEST_STORAGE_BUCKET
        value: workflow-testing-documents
      - key: TEST_STORAGE_PREFIX
        value: workflow_testing/
      - key: TEST_USER_PREFIX
        value: test_user_
      - key: TEST_USER_DOMAIN
        value: workflow-testing.local
      
      # Cost Control and Safety
      - key: ENABLE_COST_MONITORING
        value: true
      - key: DAILY_COST_LIMIT
        value: 50.00
      - key: ALERT_ON_COST_THRESHOLD
        value: true
      - key: ENABLE_AUTO_CLEANUP
        value: true
      - key: CLEANUP_INTERVAL
        value: 3600
      - key: MAX_TEST_DATA_AGE
        value: 86400
      
      # Worker optimizations
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      
      # Monitoring and Logging
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: ENABLE_DEBUG_LOGGING
        value: true
      - key: ENABLE_METRICS_COLLECTION
        value: true
      - key: METRICS_INTERVAL
        value: 60
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
      - key: ENABLE_ERROR_TRACKING
        value: true
      - key: ERROR_SAMPLE_RATE
        value: 1.0
