services:
  - type: web
    name: insurance-navigator-api
    env: docker
    plan: free
    dockerfilePath: ./config/docker/Dockerfile
    region: oregon
    branch: staging
    port: 8000
    healthCheckPath: /health
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, Accept, Origin, X-Requested-With, x-client-info, apikey, x-user-id"
      - path: /*
        name: Access-Control-Expose-Headers
        value: "Content-Length, Content-Range"
      - path: /*
        name: Access-Control-Max-Age
        value: "7200"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Vary
        value: "Origin"
    # Render optimizations for cold starts and timeouts
    buildCommand: "echo 'Using Docker build - no additional build command needed'"
    preDeployCommand: "echo 'Pre-deploy optimization complete'"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2 --timeout-keep-alive 75 --timeout 120"
    healthCheckTimeout: 120
    numReplicas: 1
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ASYNCPG_DISABLE_PREPARED_STATEMENTS
        value: "1"
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: SECURITY_BYPASS_ENABLED
        value: false
      - key: API_BASE_URL
        value: ***REMOVED***
      # Render startup optimizations
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: UVICORN_WORKERS
        value: "2"
      - key: STARTUP_TIMEOUT
        value: "120"
      - key: KEEP_ALIVE
        value: "75"
      - key: MAX_REQUESTS
        value: "1000"
      - key: MAX_REQUESTS_JITTER
        value: "100"
      # Add proxy timeouts
      - key: RENDER_PROXY_TIMEOUT
        value: "120"
      - key: RENDER_PROXY_CONNECT_TIMEOUT
        value: "60"