[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54325

[inbucket]
enabled = true
port = 54326

[functions.upload-handler]
verify_jwt = true
import_map = "./functions/_shared/import_map.json"

[functions.progress-tracker]  
verify_jwt = false
import_map = "./functions/_shared/import_map.json"

[functions.processing-webhook]
verify_jwt = false
import_map = "./functions/_shared/import_map.json"

[functions.doc-processor]
verify_jwt = true
import_map = "./functions/_shared/import_map.json"

[functions.link-assigner]
verify_jwt = false
import_map = "./functions/_shared/import_map.json"

[functions.doc-parser]
verify_jwt = false
import_map = "./functions/_shared/import_map.json"

[functions.vector-processor]
verify_jwt = false
import_map = "./functions/_shared/import_map.json" 