# Production Configuration for 003 Worker Refactor
# This file contains all production environment configuration

# Environment Configuration
environment: production
debug: false
testing: false

# Database Configuration
database:
  url: ${DATABASE_URL}
  schema: upload_pipeline
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600

# API Server Configuration
api:
  host: 0.0.0.0
  port: 8000
  workers: 8
  reload: false
  cors_origins:
    - "https://accessa.ai"
    - "https://app.accessa.ai"
  trusted_hosts:
    - "accessa.ai"
    - "app.accessa.ai"
    - "*.render.com"

# Worker Configuration
worker:
  max_jobs: 50
  poll_interval: 5
  max_retries: 3
  retry_delay: 10
  health_check_interval: 30
  graceful_shutdown_timeout: 60

# External Services Configuration
external_services:
  llamaparse:
    api_url: ${LLAMAPARSE_API_URL}
    api_key: ${LLAMAPARSE_API_KEY}
    timeout: 120
    max_retries: 3
    retry_delay: 5
  
  openai:
    api_url: ${OPENAI_API_URL}
    api_key: ${OPENAI_API_KEY}
    timeout: 60
    max_retries: 3
    retry_delay: 5
    batch_size: 256
    rate_limit_delay: 1

# Storage Configuration
storage:
  supabase:
    url: ${SUPABASE_URL}
    anon_key: ${SUPABASE_ANON_KEY}
    service_role_key: ${SUPABASE_SERVICE_ROLE_KEY}
    storage_url: ${SUPABASE_STORAGE_URL}
  
  buckets:
    raw:
      name: raw
      public: false
      max_file_size: 268435456  # 256MB
      allowed_mime_types:
        - application/pdf
    
    parsed:
      name: parsed
      public: false
      max_file_size: 10485760   # 10MB
      allowed_mime_types:
        - text/markdown
        - text/plain

# Monitoring Configuration
monitoring:
  enabled: true
  log_level: INFO
  log_format: json
  
  metrics:
    enabled: true
    collection_interval: 30
    retention_days: 90
  
  alerting:
    enabled: true
    slack_webhook: ${SLACK_WEBHOOK_URL}
    email_notifications: ${EMAIL_NOTIFICATIONS}
  
  health_checks:
    enabled: true
    interval: 30
    timeout: 10
    failure_threshold: 3

# Security Configuration
security:
  authentication:
    enabled: true
    jwt_secret: ${JWT_SECRET}
    jwt_expiry: 3600
  
  authorization:
    enabled: true
    rls_enabled: true
  
  encryption:
    enabled: true
    algorithm: AES-256-GCM
  
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 200

# Performance Configuration
performance:
  caching:
    enabled: true
    redis_url: ${REDIS_URL}
    default_ttl: 3600
  
  optimization:
    database_query_timeout: 30
    max_concurrent_requests: 100
    request_timeout: 60
  
  scaling:
    auto_scaling: true
    min_instances: 2
    max_instances: 10
    scale_up_threshold: 70
    scale_down_threshold: 30

# Backup and Recovery Configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention_days: 30
  storage_location: ${BACKUP_STORAGE_LOCATION}
  
  recovery:
    enabled: true
    rto_target: 3600  # 1 hour
    rpo_target: 86400  # 24 hours

# Deployment Configuration
deployment:
  strategy: rolling
  max_unavailable: 1
  max_surge: 2
  
  health_check:
    path: /health
    initial_delay: 30
    period: 10
    timeout: 5
    failure_threshold: 3
    success_threshold: 1
  
  rollback:
    enabled: true
    automatic: true
    health_check_failure_threshold: 3
    rollback_timeout: 300

# Testing Configuration
testing:
  enabled: true
  e2e_tests:
    enabled: true
    schedule: "0 */6 * * *"  # Every 6 hours
    timeout: 1800  # 30 minutes
  
  performance_tests:
    enabled: true
    schedule: "0 1 * * *"  # Daily at 1 AM
    load_test_duration: 900  # 15 minutes
  
  security_tests:
    enabled: true
    schedule: "0 3 * * *"  # Daily at 3 AM
    vulnerability_scan: true
    penetration_test: false

# Incident Response Configuration
incident_response:
  enabled: true
  escalation:
    level1_timeout: 300  # 5 minutes
    level2_timeout: 900  # 15 minutes
    level3_timeout: 3600  # 1 hour
  
  notifications:
    slack: true
    email: true
    pagerduty: ${PAGERDUTY_INTEGRATION_KEY}
  
  runbooks:
    enabled: true
    location: /opt/runbooks
    auto_update: true

# Compliance Configuration
compliance:
  hipaa:
    enabled: true
    audit_logging: true
    data_encryption: true
    access_controls: true
  
  gdpr:
    enabled: true
    data_retention: true
    right_to_forget: true
  
  soc2:
    enabled: false
    audit_logging: true
    security_controls: true

# Cost Optimization Configuration
cost_optimization:
  enabled: true
  monitoring:
    enabled: true
    alert_threshold: 1000  # $1000/month
  
  optimization:
    auto_scaling: true
    resource_rightsizing: true
    unused_resource_cleanup: true
  
  reporting:
    enabled: true
    frequency: daily
    recipients: ${COST_REPORTING_EMAILS}
